version: '2'
services:
  webapp-app:
    image: webapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://webapp-mysql:3306/webapp?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://webapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://webapp-elasticsearch:9200
    ports:
      - 8080:8080
  webapp-mysql:
    extends:
      file: mysql.yml
      service: webapp-mysql
  webapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: webapp-elasticsearch
